### ISSUE TITLE
Add autoremove command

### ISSUE THREAD

**Issue by Futrime** [LiteLDev/Lip#37]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Add autoremove command like apt autoremove.

**Describe alternatives you've considered**

**Additional context**

**Comment by Futrime** [comment]
I'm not clear about which tooths to be deleted. Should I delete headless dependencies? Should I delete dependents?

**Comment by harry-xi** [comment]
> I'm not clear about which tooths to be deleted. Should I delete headless dependencies? Should I delete dependents?

1. Let tooth actively declare itself as a running dependency of other teeth only, and is automatically removable when no package depends on it.
2. Provide the option at installation time to let the user decide if the packages that tooth depends on are installed as runtime dependencies only. These packages can be automatically removed when they have no other dependencies and are not installed in a mode other than as runtime dependencies only.
