### ISSUE TITLE
cmd shortcuts

### ISSUE THREAD

**Issue by lgc2333** [LiteLDev/Lip#66]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

add some cmd shortcuts like `lip i` (`lip install`)

**Describe alternatives you've considered**

**Additional context**

**Comment by Futrime** [comment]
Please provide a list of command aliases for reference.

**Comment by lgc2333** [comment]
| shortcuts or aliases | original |
|:-|:-|
| `lip e` / `lip run` | `lip exec` |
| `lip i` / `lip in` / `lip add` | `lip install` |
| `lip un` / `lip rm` / `lip del` | `lip uninstall` |
| `lip ls` | `lip list` |
| `lip info` / `lip inf` | `lip show` |
| `lip tth` | `lip tooth` |
