### ISSUE TITLE
`lip init`指令应引导用户初步填写元数据

### ISSUE THREAD

**Issue by lgc2333** [LiteLDev/Lip#80]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

差不多就像`npm init`那样

如果不喜欢可以不做，也可以做一个选项比如 `-i`(interactive) 启用该功能

**Describe alternatives you've considered**

**Additional context**

**Comment by Futrime** [comment]
Please help me decide which fields to ask user to fill.

**Comment by harry-xi** [comment]
> Please help me decide which fields to ask user to fill.
# 

1. Is it possible to try to get the repository address directly from the folder's git? 
  - If this is possible, provide a confirmation message. When the user thinks this is incorrect, request input from the user.
  - If not, then only manual input is available

2. version

  It seems appropriate to also consider the need for packages that require the upload of lip registration libraries, so there will be:

3. infomations：
  - name (Folder names can be provided as default values)
  - license 
  - author 
  - description （This item should be optional）
  - tag （This item should be optional）

> In fact, just consider the fields you leave empty in the default generated tooth.json
