### ISSUE TITLE
tooth.json建议修改dependencies处的地址表述方式

### ISSUE THREAD

**Issue by yqs112358** [LiteLDev/Lip#85]
<img width="314" alt="image" src="https://user-images.githubusercontent.com/37969157/228842235-a3d27769-bd9e-44dd-8fed-a1bf045537bf.png">
如图，这里的地址表示方式感觉可以改进一下。

比如我可以国内国外分开提供镜像（虽然说直接改goproxy也行，但是可能有场景需要比如国内外仓库中包的内容有所不同）
或者可以为某些资源提供更快速的下载地址等；或者给出多个地址万一有失效可以进行替换，不至于整个依赖链条直接断掉。

直接把地址作为key不太好，有Registry的包管理可以用这么设计（比如package.json），因为他们能保证下载渠道唯一，并且包唯一。既然Lip是基于地址储存，最好能给出可以转圜的空间。

可以修改为：
```json
"dependencies": [
    {
        "name": "LiteLoaderBDS",
        "version": [ "2.12.x"],
        "url": ["github.com/Tooth-Hub/LiteLoaderBDS", "可以加新的"]
    },
]
```
其中name还可以在地址失效时，从registry查询可用结果

**Comment by yqs112358** [comment]
registry确实不是必选项，但是作为包管理器做一些提高鲁棒性的设计没有坏处。面向公众和生产环境的设计预留冗余是非常正常的事情。如果可以保证设施在出现一些小异常的时候仍然正常运行，会更好。

备用地址和name仅在首位不可用的时候逐个进行尝试，如果尝试成功继续进行解析。对解析依赖整体逻辑没有什么影响。

**Comment by RimuruChan** [comment]
> registry确实不是必选项，但是作为包管理器做一些提高鲁棒性的设计没有坏处。面向公众和生产环境的设计预留冗余是非常正常的事情。如果可以保证设施在出现一些小异常的时候仍然正常运行，会更好。
> 
> 备用地址和name仅在首位不可用的时候逐个进行尝试，如果尝试成功继续进行解析。对解析依赖整体逻辑没有什么影响。

这不是提高稳定性，是纯粹的无意义设计，不但违反了唯一仓库地址原则，还强依赖与registry。

registry不只有ll的registry，你也无法保证name一定能得到正确的解析，用户甚至可能因此受到攻击。

增加无意义的设计不能使项目更好，只能堆起屎山，勒住更有意义方向开发的手脚

**Comment by yqs112358** [comment]
目前基于github的仓库，在正常情况下确实不存在太大问题。即使仓库更名，原名字也仍然可以访问，不会发生依赖无法处理的情况。
但是，在Lip设计之初是否考虑到了如下这些问题：
- 使用非github仓库（比如自建gitlab甚至gitee）作为储存库？非github平台不一定提供这种保证。
- 上游包作者删库，或者自建gitlab无法访问导致依赖链条断裂，下游未及时更新索引，导致依赖失效。
- 删库者的直接下游无法及时更新索引，导致更下游无法修复依赖。
- 上游作者在包中引入供应链攻击代码，下游如何进行规避？
- 下游作者由于忙碌或者跑路等无法自行修复索引，目前设计如何靠外部力量帮助所有下游作者修复？目前的设计根本无法得知有哪些下游作者，更不用说进行通知。

一个足够稳定的包管理需要考虑到所有意外情况该如何处理，而不是只考虑正常工作的情况。 **插件开发者无法保证永远稳定工作，新进入或者离开是很正常的事情，无法被维护的依赖也是很正常的事情。如何保证这些依赖在万一出现失效的情况下不会出现大的问题？** 我认为现在的设计无法弥补这个缺陷。

------

你也许认为这样的更改是无意义甚至是屎山的，其实我也有些这么认为。因为在我的认识中这样的依赖管理机制是难以处理异常情况的，也就是说这个依赖机制本身是有问题的。
可以考虑一下为什么apt pip npm等一众包管理器一律采用了索引仓库的设计。很简单，索引仓库可以解决上面提到的所有问题。以npm为例，npm仅仅使用package.lock文件储存上一次下载的地址，为了再次安装时的能够起到一定的加速。不过当给出的地址无法解析时，npm最终仍然会到registry中搜索并安装对应的包，整个过程不会存在依赖失效的情况。同时索引仓库为所有镜像站所共享，不同区域可以使用不同的镜像站加速。另外如果出现删库或者供应链攻击，对于Lip这样规模的仓库完全可以由社区进行fork并进行自动化的修复。

我个人认为，此Issue提出的只是一种可能的问题解决方案，然而更好的解决方案是修改整个依赖机制的设计。将依赖机制修改为以Registry为中心，索引仓库的设计，跟vcpkg更像。可以看看vcpkg是如何设计的：
https://github.com/microsoft/vcpkg/tree/master/ports
在不同的镜像站之间，同步registry即可。同时社区也可以自建registry，可以收集常用的registry并内置于lip中。如果网络不通畅，对registry的访问也可以同样通过go proxy等机制进行穿透。这样的设计显然更为有效且稳定。

------

Lip作为LL3最为重要的基础设施，必须要保证可以在大部分情况下都可以稳定工作，否则LL的使用将遇到极大的问题。我认为此问题需要认真对待

**Comment by yqs112358** [comment]
我认为此设计是否“无意义”或者“屎山”仍然有待讨论，可以再等待一段时间让其他用户看看并进行评判

**Comment by WangYneos** [comment]
本身就不是中心化的路，在享受去中心化的遍历时，自身就有一定局限性，上游依赖被弃用甚至删除的案例也不是不存在，下游开发者如果仍然在维护项目会及时解决依赖链断裂的问题。
此外，register内的alias是随时可变的，随时可以修改名字或目标，也可能有自建registry的需求，万一发生重名，如果仍然按照registry alias进行依赖解析，则会带来意外的情况

**Comment by RimuruChan** [comment]
> 我认为此设计是否“无意义”或者“屎山”仍然有待讨论，可以再等待一段时间让其他用户看看并进行评判

用户只考虑自己的利益，不会在乎程序的设计，程序的安全性要如何保证，他们就算在乎也受知识储备的限制，一个功能做的好不好可以让用户评判，一个程序设计好不好用户是无法评判的。

**Comment by yqs112358** [comment]
@RimuruChan 希望我们以后可以更客观的讨论问题，而不是在讨论的过程中就带上对想法的一些主观评价，如“屎山”，“无意义”，“冗余” 等。

**Comment by RimuruChan** [comment]
当然，我也很欢迎你指出我评论中的不当之处，说其完全无意义确实是过头了，但是我依然其意义不大，且弊大于利。
